version: "3.7"

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:4.8.1
    restart: unless-stopped
    volumes:
     - ./data/uploads:/app/uploads
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "http://${ROCKETCHAT_HOST}:3000"
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.rule: Host(`${ROCKETCHAT_HOST}`)
      traefik.http.routers.rocketchat.entrypoints: http
    depends_on:
      - mongodb

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: unless-stopped
    volumes:
      - ./data/db:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 7017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"

  traefik:
    image: docker.io/traefik:v2.6.1
    restart: unless-stopped
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:${ROCKETCHAT_PORT}
    ports:
     - ${ROCKETCHAT_PORT}:3000
     - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - ./data/letsencrypt:/letsencrypt:rw
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
